/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AISettings: typeof import('./components/gomoku/AISettings.vue')['default']
    AIStatusPanel: typeof import('./components/gomoku/AIStatusPanel.vue')['default']
    ChessBoard: typeof import('./components/chess/board/ChessBoard.vue')['default']
    ChessEntry: typeof import('./components/chess/ChessEntry.vue')['default']
    ChessPiece: typeof import('./components/chess/board/ChessPiece.vue')['default']
    ConfirmDialog: typeof import('./components/gomoku/ConfirmDialog.vue')['default']
    GameControlPanel: typeof import('./components/gomoku/GameControlPanel.vue')['default']
    GameInfoHeader: typeof import('./components/gomoku/GameInfoHeader.vue')['default']
    GameSettings: typeof import('./components/gomoku/GameSettings.vue')['default']
    GlobalSettings: typeof import('./components/GlobalSettings.vue')['default']
    Gomoku: typeof import('./components/gomoku/Gomoku.vue')['default']
    GomokuBoard: typeof import('./components/gomoku/GomokuBoard.vue')['default']
    HomeButton: typeof import('./components/HomeButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WinDialog: typeof import('./components/gomoku/WinDialog.vue')['default']
  }
}
